# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b5f97405a96309d49b3eaa6575e2338df2fdadc1ae9b988ff24999559cd6ee2930d6b3d75ea359514c062552f0986b3ff81b4485254d7f1f90a5d7e87afff42

test:
  secret_key_base: 57024f1d669be4bdbfc9c1506521de8411aa92e044b3c583909698d9a1d6c166ddeef14920700908f4a815f216c9c8f12c4744554fcb4469719224d1df72dfea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
